{
 "title": "Router stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "router_uptime",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "io",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "SELECT \"io\" FROM \"router_cpu\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "irq",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "SELECT \"io\" FROM \"router_cpu\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "nic",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "SELECT \"io\" FROM \"router_cpu\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "nic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "sirq",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "SELECT \"io\" FROM \"router_cpu\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "sys",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "SELECT \"sys\" FROM \"router_cpu\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "usr",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "SELECT \"sys\" FROM \"router_cpu\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "usr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_mem",
     "select": [
      [
       { "params": [ "free_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_mem",
     "query": "SELECT \"used_kb\", \"used_swap_kb\" FROM \"router_mem\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "used_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "br0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net",
     "query": "SELECT min(\"recv_mbps\") FROM \"router_net\" WHERE (\"interface\" = 'br0') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "br0" }
     ]
    },
    {
     "alias": "eth0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net",
     "query": "SELECT min(\"recv_mbps\") FROM \"router_net\" WHERE (\"interface\" = 'br0') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "bcmsw",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net",
     "query": "SELECT min(\"recv_mbps\") FROM \"router_net\" WHERE (\"interface\" = 'br0') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "bcmsw" }
     ]
    },
    {
     "alias": "eth4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_net",
     "query": "SELECT min(\"recv_mbps\") FROM \"router_net\" WHERE (\"interface\" = 'br0') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth4" }
     ]
    }
   ]
  },
  {
   "title": "External Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "nu.nl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_ping_ext",
     "query": "SELECT \"ms\" FROM \"router_ping_ext\" WHERE (\"dst\" = 'www.dn.se') AND $timeFilter",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "www.nu.nl" }
     ]
    },
    {
     "alias": "google.com",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_ping_ext",
     "query": "SELECT \"ms\" FROM \"router_ping_ext\" WHERE (\"dst\" = 'www.dn.se') AND $timeFilter",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "www.google.com" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "2.4 GHz",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_temp",
     "select": [
      [
       { "params": [ "temp_24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "5 GHz",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_temp",
     "select": [
      [
       { "params": [ "temp_50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wireless Clients 2.4 GHz",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2.4 GHz",
     "measurement": "router_assoclist_24",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wireless Clients 5 GHz",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "5 GHz",
     "measurement": "router_assoclist_50",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}